### PR TITLE
add jk60rgb

### PR DESCRIPTION
**Pull request by alabahuy**
## Description

add jk60rgb

## QMK Pull Request

https://github.com/qmk/qmk_firmware/pull/24485

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] I have tested this keyboard definition with firmware on a device.**(MANDATORY)**
- [ ] VIA keymap uses custom menus
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Cipulot** [comment]
@alabahuy not sure if it was an error or what, but `qmk.json` shouldn't be there for the purpose of the PR.

**Comment by alabahuy** [comment]
> @alabahuy not sure if it was an error or what, but `qmk.json` shouldn't be there for the purpose of the PR.

sorry, its automatic add in my repo. i'll remove that

**Comment by Cipulot** [comment]
> > @alabahuy not sure if it was an error or what, but `qmk.json` shouldn't be there for the purpose of the PR.
> 
> sorry, its automatic add in my repo. i'll remove that

It's not to be deleted, but rather to not modify the one that was in the repo itself, should probably resync your fork with main and check on that.

**Comment by alabahuy** [comment]
> > > @alabahuy not sure if it was an error or what, but `qmk.json` shouldn't be there for the purpose of the PR.
> > 
> > 
> > sorry, its automatic add in my repo. i'll remove that
> 
> It's not to be deleted, but rather to not modify the one that was in the repo itself, should probably resync your fork with main and check on that.

I will create a new PR, I will delete this PR.

**Pull request closed without merging**
